import type { Metadata } from "next";
import { Pixelify_Sans, Rubik_Pixels } from "next/font/google";
import "./globals.css";

const pixelifySans = Pixelify_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const rubikPixels = Rubik_Pixels({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-pixels",
  display: "swap",
});

export const metadata: Metadata = {
  title: "nina & rores wedding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pixelifySans.variable} ${rubikPixels.variable}`}>
      <body className="font-sans antialiased bg-[#bbc1e8]">
        {children}
      </body>
    </html>
  );
}
